# Generated by Django 4.2.8 on 2023-12-13 18:12

from django.db import migrations, models
import django.db.models.deletion

def Populate_status(app, schemaediter):
  statuses = {
    "published" : "Apost vissible to all on site",
    "draft" : "post only the auther can see",
    "archived" : 'a post only visible to loged in users'
  }
  Status = apps.get_model('posts', 'status')
  for key, value in statuses.items():
    status_obj = Status(name=key, description=value)
    status_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=111)),
                ('description', models.CharField(max_length=111)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.status'),
        ),
    ]
